INSERT INTO equipos(nombre,id_pais) VALUES ('Audi Sport Team Joest',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Pescarolo Sport',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Panoz Motorsports',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('TV Asahi Team Dragon',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Viper Team Oreca',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Corvette Racing / Gary Pratt',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Carsport Holland',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Konrad Motorsport',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Taisan Advan',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Skea Racing International',13);
INSERT INTO equipos(nombre,id_pais) VALUES ('Seikel Motorsport',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team DAMS',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Mopar Team Oreca',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Cadillac',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Perspective Racing',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Renstal Excelsior',20);
INSERT INTO equipos(nombre,id_pais) VALUES ('Multimatic Motorsport',34);
INSERT INTO equipos(nombre,id_pais) VALUES ('Welter Rachel',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Manthey (Gunnar Racing)',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Haberthur Racing',191);
INSERT INTO equipos(nombre,id_pais) VALUES ('Maury Laribiere Jean Luc',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Larbre Competition',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Racing Engineering',59);
INSERT INTO equipos(nombre,id_pais) VALUES ('Michael Colucci',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Freisinger Motorsport',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Goh (Chamberlain)',50);
INSERT INTO equipos(nombre,id_pais) VALUES ('Paul Belmondo Racing',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Welter Gerard',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('ROC Competition',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Bonnet Didier',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Johansson Matthews Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Rafanelli',106);
INSERT INTO equipos(nombre,id_pais) VALUES ('Konrad Racing for Holland',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('SMG Compétition',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Thomas Bscher Promotions',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Dick Barbour Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Den Bla Avis',50);
INSERT INTO equipos(nombre,id_pais) VALUES ('Audi Sport North America',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Bentley',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Playstation',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('ROC Auto',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Corvette Racing Gary Pratt',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Larbre Competition Chereau',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('DAMS',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('PK Sport Ltd Ricardo',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Luc Alphand Aventures',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Saleen Allen Speedlab',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Aspen Knolls MCR',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('RML',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Equipe de France',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Dick Barbour',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('S+R Rowan Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('MG Sport & Racing Ltd',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Roock Knighthawk Racing',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Ascari',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Den Bla Avis Team Goh',50);
INSERT INTO equipos(nombre,id_pais) VALUES ('Racing For Holland',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Johansson Motorsport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Champion Racing Dave Maraj',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Del Bello Noel',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Playstation Team Oreca',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Audi Sport Japan Team Goh',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Corvette Racing Pratt & Miller',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Equipe de France FFSA',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Courage Competition',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('The Racers Group / Kevin Buckler',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Noel Del Bello',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Ray Mallock Limited',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Spyker Automobielen NL',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('PK Sport Ltd',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Orbit Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Auto Palace',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Dewalt Racesports Salisbury',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('JMB Competition',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Prodrive',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Carsport Holland',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Knight Hawk Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Autoexe Motorsport',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('MBD Sportscar Team',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Kondo Racing',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Riley & Scott Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('JML Team Panoz',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Veloqx Prodrive Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Alex Job Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('RN Motorsport',50);
INSERT INTO equipos(nombre,id_pais) VALUES ('PK Sport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Automotive Durango',106);
INSERT INTO equipos(nombre,id_pais) VALUES ('JMB Racing',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Risi Competizione',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('T2M Motorsport',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('XL Racing',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Scorp Motorsport Communication',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Carsport America',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Intersport Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Gerard Welter',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Bucknum Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Edouard Sezionale',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Nasamax',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Audi Sport UK',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Orange Spyker',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Graham Nash Motorsport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Rachel Welter',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Lister Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Audi Sport UK Team Veloqx',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Corvette Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Prodrive Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Dale White Lightning Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Choroq Racing Team',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('The Racers Group',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Cirtek Motorsport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Taurus Sports Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Chamberlain - Synergy Motorsport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Thierry Perrier',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Orbit Racing - Rodger Hawley',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Barron Connor Racing',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Epsilon Sport',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Zytek Engineering Ltd',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Rollcentre Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Morgan Works Race Team',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Champion',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Champion Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Audi Playstation Team Oreca',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Aston Martin Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('White Lightning Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Flying Lyzard Motorsports',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Creation Autosportif Ltd',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Raymond Narac',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Sebah Automotive Ltd',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Kruse Motorsport Ltd',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Jim Gainer International',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Pierre Bruneau',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Miracle Motorsports',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('G-Force Racing',20);
INSERT INTO equipos(nombre,id_pais) VALUES ('BMS Scuderia Italia',106);
INSERT INTO equipos(nombre,id_pais) VALUES ('Spyker Squadron b.v.',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Scuderia Ecosse',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Jota - Zytek Engineering Ltd',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Racesport Peninsula TVR',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Russian Age Racing',169);
INSERT INTO equipos(nombre,id_pais) VALUES ('Acemco Motorsports',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Binnie Motosports',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team LNT',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Barazi Epsilon',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Ice Pol Racing Team',20);
INSERT INTO equipos(nombre,id_pais) VALUES ('Chamberlain Synergy Motorsport',159);
INSERT INTO equipos(nombre,id_pais) VALUES ('Swiss Spirit',191);
INSERT INTO equipos(nombre,id_pais) VALUES ('Lister Storm Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Larbre Competition Team',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Convers Menx Team',169);
INSERT INTO equipos(nombre,id_pais) VALUES ('IMSA Performance Matmut',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Multimatic Motorsport Team Panoz',34);
INSERT INTO equipos(nombre,id_pais) VALUES ('Jloc Isao Noritake',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team PeugeotTotal',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Charouz Racing System',214);
INSERT INTO equipos(nombre,id_pais) VALUES ('Aston Marting Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Oreca',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('AMR BMS',214);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Modena',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Autorlando Sport',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('AF Corse',106);
INSERT INTO equipos(nombre,id_pais) VALUES ('PSI Experience',20);
INSERT INTO equipos(nombre,id_pais) VALUES ('AMR Larbre Competition',214);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Bruichladdich Radical',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Saulnier Racing',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Quifel ASM Team',159);
INSERT INTO equipos(nombre,id_pais) VALUES ('Kruse Motorsport',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('GPC Sport',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Oreca Matmut',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Van Merksteijn Motorsport',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Essex',50);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Corvette Racing',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('BMS Scuderis Italia',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Farnbacher Racing',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Felbermayr-Proton',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Flying Lizard Motorsports',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Dome Racing Team',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Epsilon Euskadi',59);
INSERT INTO equipos(nombre,id_pais) VALUES ('Tokai University',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Autocon',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Speedy Racing Team Sebah',191);
INSERT INTO equipos(nombre,id_pais) VALUES ('Trading Performance',191);
INSERT INTO equipos(nombre,id_pais) VALUES ('Kruse Schiller Motorsport',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Embassy Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Vitaphone Racing Team',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Speedy Racing Team',191);
INSERT INTO equipos(nombre,id_pais) VALUES ('Virgo Motorsport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Terramos',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Interprogressbank',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Peugeot Sport Total',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('AMR Eastern Europe',214);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Oreca Matmut AIM',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Kolles',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Signature Plus',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Corvette Racing USA',61);
INSERT INTO equipos(nombre,id_pais) VALUES ('Oak Racing',66);
INSERT INTO equipos(nombre,id_pais) VALUES ('Strakka Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('JMW Motorsport',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Snoras Spyker Squadron',149);
INSERT INTO equipos(nombre,id_pais) VALUES ('Team Advanced Engineering',106);
INSERT INTO equipos(nombre,id_pais) VALUES ('Jetalliance Racing',14);
INSERT INTO equipos(nombre,id_pais) VALUES ('Navi Team Goh',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Bruichladdich Bruneau',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Racing Box SRL',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('KSM',159);
INSERT INTO equipos(nombre,id_pais) VALUES ('Quifel ASM Team PRT',159);
INSERT INTO equipos(nombre,id_pais) VALUES ('GAC Racing Team',214);
INSERT INTO equipos(nombre,id_pais) VALUES ('JLOC',108);
INSERT INTO equipos(nombre,id_pais) VALUES ('Drayson Racing',161);
INSERT INTO equipos(nombre,id_pais) VALUES ('Hankook Team Farnbacher',3);
INSERT INTO equipos(nombre,id_pais) VALUES ('Endurance Asia Team',38);
